# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cb748f09887d079b89271042c9e16cef841baef2cead858cc4e10217bbc2ecfcffc549fe1270eb7c71de9973241c8e91ecab729dcaf65144d41d4b23de5d4b3

test:
  secret_key_base: 074e3cfaa8ae36584dd135c3cf5e0d3e72c2e4bc71ce237f37725e5f6bdbab8b3da4516879187279f336ddd79b2a91cc682804c67f58f3b1f3a0024d27ffd8ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
